version: '3.4'

services:
  broker:
    image: rabbitmq:3-management-alpine
    container_name: broker
    environment:
      RABBITMQ_DEFAULT_USER: "example"
      RABBITMQ_DEFAULT_PASS: "secret"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bus
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    environment:
      SA_PASSWORD: "S3cr3t123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  vn.example.host.web:
    container_name: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    ports:
      - "8081:8081"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    links:
      - broker
      - mssql
    depends_on:
      - mssql

networks: 
    bus:
      driver: bridge